### PR TITLE
msktkrb5.cpp: make sure keytab_file is always set (fixes #76)

### LINKED ISSUE #76: try_machine_keytab_princ is not called when keytab is not exlicitly given via --keytab
running `msktutil update` without credential cache but existing keytab fails, when using default /etc/krb5.keytab or when specifying the keytab via environment:

```
$ KRB5_KTNAME=/tmp/krb5.keytab msktutil update
Error: could not find any credentials to authenticate with. Neither keytab,
default machine password, nor calling user's tickets worked. Try
"kinit"ing yourself some tickets with permission to create computer
objects, or pre-creating the computer object in AD and selecting
'reset account'.
```

However, specifying KT via --keytab works:

```
$ msktutil update --keytab /tmp/krb5.keytab 
$ 
```
We need to review c1efe42019be5ebcd42aadcc648ac3948a4f88ce

### PR DESCRIPTION
**Pull request by sckobras**
The access() checks introduced in c1efe42019be5ebcd42aadcc648ac3948a4f88ce require a valid flags->keytab_file, which was unset if using default keytab locations. This change initializes flags->keytab_file in these cases as well.

### CODE REVIEW

File: msktkrb5.cpp [hunk 1]
```diff
@@ -59,17 +59,28 @@ void get_default_keytab(msktutil_flags *flags)
...
-            /* Ignore the opening WRFILE: part */
+            /* Already includes the opening WRFILE: part */
             flags->keytab_writename = std::string(keytab_name);
         } else {
             /* No prefix to the keytab path */
             flags->keytab_writename = "WRFILE:" + std::string(keytab_name);
         }
+
+        /* Ignore opening WRFILE: part */
+        flags->keytab_file = flags->keytab_writename.substr(7);
```
Comment (michael-o) [inline msktkrb5.cpp]: Are you certain that `WRFILE:` is always prepended?

**Comment by michael-o** [comment]
Looks good to me.

File: msktkrb5.cpp (hunk 1 above)
Comment (sckobras) [inline msktkrb5.cpp]: Yes. It's not visible in the diff itself, but the code immediately preceeding the change makes sure that flags->keytab_writename is normalized to always include the WRFILE: prefix.
