### PR TITLE
Keytab entries created with wrong salt

### LINKED ISSUE #66: keytab entries created with wrong salt
msktutil creates entries with wrong salt under some circumstances:

1) --use-service-account and existing account has no userPrincipalName. In that case the sAMACountname is taken for salt creation -- but in lowercase. Example: Administrator@EXAMPLE.COM has the salt EXAMPLE.COMAdministrator, but msktutil uses EXAMPLE.COMadministrator which leads to wrong keys

2) Enterprise names will probably not work for --use-service-account (not tested)

Reported by: mproehl

### PR DESCRIPTION
**Pull request by mproehl**
this fixes #66

### CODE REVIEW

File: msktkrb5.cpp [hunk 1]
```diff
@@ -104,7 +104,7 @@ std::string get_salt(msktutil_flags *flags)
         if (flags->userPrincipalName.empty()) {
             salt = sform("%s%s",
                          flags->realm_name.c_str(),
-                         lower_accountname.c_str());
```
Comment (sckobras) [inline msktkrb5.cpp]: With this consumer of `lower_accountname` gone, maybe move it from the start of the function to the only remaining user in the `else` branch below?

Comment (michael-o) [inline msktkrb5.cpp]: @sckobras Makes sense. Only machine accounts need this.

**Comment by michael-o** [comment]
Looks good to me. Don't forget to squash commits before merging into trunk.
